export const legalProfile = {
  companyName: "[Firmenname]",
  ownerName: "[Vorname Nachname]",
  legalForm: "[Einzelunternehmen / GmbH / ...]",
  businessPurpose: "[Unternehmensgegenstand, z. B. Floristik und Handel mit Pflanzen]",
  street: "[Strasse Hausnummer]",
  postalCode: "[PLZ]",
  city: "[Ort]",
  country: "Oesterreich",
  phone: "[Telefonnummer]",
  email: "[E-Mail-Adresse]",
  website: "https://[domain.tld]",
  uidNumber: "[ATU12345678]",
  companyRegisterNumber: "[FN 123456 x]",
  companyRegisterCourt: "[Firmenbuchgericht]",
  supervisoryAuthority: "[Zustaendige Behoerde]",
  chamber: "[Wirtschaftskammer / Berufskammer]",
  dataProtectionContact: "[Datenschutz-Kontakt, falls abweichend]",
  hostingProvider: "[Hosting-Anbieter]",
  hostingLocation: "[Serverstandort, z. B. Oesterreich / Deutschland / EU]",
  analyticsTool: "Google Analytics 4",
  analyticsOptOutLink: "https://tools.google.com/dlpage/gaoptout?hl=de",
  analyticsEnabled: false,
  storagePeriodGeneral:
    "Personenbezogene Daten werden nur so lange gespeichert, wie es fuer die jeweiligen Zwecke erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen.",
  lastUpdated: "[TT.MM.JJJJ]",
} as const;
