export const legalProfile = {
  companyName: "Blumenatelier „Let It Bloom“",
  ownerName: "Wolfgang Gruber",
  legalForm: "Einzelunternehmen",
  businessPurpose: "Florist / Blumenhändler",
  street: "Alleestraße 42",
  postalCode: "2103",
  city: "Langenzersdorf",
  country: "Österreich",
  phone: "+43 664 230 34 27",
  email: "wgruber@outlook.at",
  website: "https://www.let-it-bloom.at",
  uidNumber: "[UID-NUMMER EINFÜGEN]",
  companyRegisterNumber: "[FIRMENBUCHNUMMER EINFÜGEN ODER ENTFERNEN]",
  companyRegisterCourt: "[FIRMENBUCHGERICHT EINFÜGEN ODER ENTFERNEN]",
  supervisoryAuthority: "Bezirkshauptmannschaft Korneuburg [ANPASSEN FALLS ABWEICHEND]",
  chamber: "Wirtschaftskammer Niederösterreich, Landesinnung der Gärtner und Floristen [ANPASSEN FALLS ABWEICHEND]",
  dataProtectionContact: "wgruber@outlook.at",
  hostingProvider: "Vercel Inc.",
  hostingLocation: "USA / Globale Server (Datenverarbeitung standardmäßig in der EU für europäische Nutzer)",
  analyticsTool: "Vercel Analytics",
  analyticsOptOutLink: "",
  analyticsEnabled: true,
  storagePeriodGeneral:
    "Personenbezogene Daten werden nur so lange gespeichert, wie es für die jeweiligen Zwecke erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen.",
  lastUpdated: "Mai 2026",
} as const;
