export const legalProfile = {
  companyName: "Blumenatelier „Let It Bloom“",
  ownerName: "Wolfgang Gruber",
  legalForm: "Einzelunternehmen",
  businessPurpose: "Blumenhändler",
  street: "Alleestraße 42",
  postalCode: "2103",
  city: "Langenzersdorf",
  country: "Österreich",
  phone: "+43 664 230 34 27",
  email: "wgruber@outlook.at",
  website: "https://www.let-it-bloom.at",
  uidNumber: "ATU68198504",
  supervisoryAuthority: "Bezirkshauptmannschaft Korneuburg",
  chamber: "Wirtschaftskammer Niederösterreich, Landesinnung der Gärtner und Floristen ",
  professionalRegulations: "Gewerbeordnung (GewO) – abrufbar im Rechtsinformationssystem des Bundes (RIS) unter https://www.ris.bka.gv.at",
  blattlinie: "Information über die floristischen Dienstleistungen, Arrangements und Produkte des Blumenateliers sowie die Förderung der geschäftlichen Aktivitäten des Unternehmens.",
  web3formsProcessor: "Web3Forms (Lintel Technologies Private Limited, Hyderabad, Indien)",
  web3formsPolicy: "https://web3forms.com/privacy",
  dataProtectionContact: "wgruber@outlook.at",
  hostingProvider: "Vercel Inc.",
  hostingLocation: "USA / Globale Server (Datenverarbeitung standardmäßig in der EU für europäische Nutzer)",
  analyticsTool: "Vercel Analytics",
  analyticsOptOutLink: "",
  analyticsEnabled: true,
  storagePeriodGeneral:
    "Personenbezogene Daten werden nur so lange gespeichert, wie es für die jeweiligen Zwecke erforderlich ist oder gesetzliche Aufbewahrungspflichten bestehen.",
  lastUpdated: "Mai 2026",
} as const;
